from nash_grid import NashGrid

# pd = NashGrid("../tests/pd.txt")
# print("test file 1:")
# pd.print_pure_strategies()
# print(pd.payout_grid)
# print(pd.col_labels)
# print(pd.remove_dominated_moves())
# print(pd.payout_grid)
# print(pd.col_labels)
# pd.print_pure_strategies()

# pd2 = NashGrid("../tests/pd2.txt")
# print("test file 2:")
# print(pd2.payout_grid)
# print(pd2.col_labels)
# print(pd2.remove_dominated_moves())
# print(pd2.payout_grid)

# pd3 = NashGrid("../tests/pd3.txt")
# print("test file 3:")
# print(pd3.payout_grid)
# print(pd3.col_labels)
# print(pd3.remove_dominated_moves())
# print(pd3.payout_grid)
# pd3.print_pure_strategies()

# wd1 = NashGrid("../tests/wd1.txt")
# print("test file 4:")
# print(wd1.payout_grid)
# print(wd1.col_labels)
# print(wd1.remove_dominated_moves())
# print(wd1.payout_grid)
# wd1.print_pure_strategies()

# wd2 = NashGrid("../tests/wd2.txt")
# print("test file 5:")
# wd2.print_pure_strategies()
# print(wd2.payout_grid)
# print(wd2.col_labels)
# print(wd2.remove_dominated_moves())
# print(wd2.payout_grid)
# wd2.print_pure_strategies()

ms1 = NashGrid("../tests/ms1.txt")
print("test file 6:")
ms1.print_pure_strategies()
print(ms1.payout_grid)
print(ms1.col_labels)
print(ms1.remove_dominated_moves())
print(ms1.payout_grid)
ms1.print_pure_strategies()
ms1.print_mixed_strategies()
